databases:
  - name: cosound-db
    plan: free
    databaseName: cosound
    user: cosound

services:
  - type: web
    plan: free
    name: cosound-server
    runtime: python
    rootDir: src/server
    buildCommand: '../../bin/buildserver_prod.sh'
    startCommand: '../../bin/runserver_prod.sh'
    envVars:
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: cosound-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: UV_VERSION
        value: 0.9.18
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: FIRST_ADMIN_EMAIL
        sync: false
      - key: FIRST_ADMIN_USERNAME
        sync: false
      - key: FIRST_ADMIN_PASSWORD
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false

